"""add_caste_locked_to_tenants

Revision ID: 815bd765c837
Revises: f52613eb5836
Create Date: 2026-03-21 14:13:20.312210
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815bd765c837'
down_revision = 'f52613eb5836'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('caste_locked', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='When enabled, members only see profiles of their own caste'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'caste_locked')
    # ### end Alembic commands ###
