"""add_tenant_payment_fields

Revision ID: f52613eb5836
Revises: 011
Create Date: 2026-03-13 18:31:37.197694
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f52613eb5836'
down_revision = '011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('file_records', 'object_key',
               existing_type=sa.VARCHAR(length=1024),
               comment='Full S3 object key including prefix',
               existing_nullable=False)
    op.alter_column('file_records', 'original_filename',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('file_records', 'mime_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('file_records', 'size_bytes',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('file_records', 'purpose',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='profile_photo | horoscope')
    op.alter_column('file_records', 'scan_status',
               existing_type=postgresql.ENUM('pending', 'clean', 'infected', 'error', name='scanstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('file_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_file_records_profile', table_name='file_records')
    op.create_index(op.f('ix_file_records_profile_id'), 'file_records', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'file_records', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'file_records', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('member_subscriptions', 'price_paid_inr',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Price snapshot at time of assignment for billing history accuracy',
               existing_nullable=False)
    op.alter_column('member_subscriptions', 'starts_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Subscription start date (UTC)',
               existing_nullable=False)
    op.alter_column('member_subscriptions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Subscription expiry date = starts_at + duration_months',
               existing_nullable=False)
    op.alter_column('member_subscriptions', 'status',
               existing_type=postgresql.ENUM('active', 'expired', 'cancelled', name='subscription_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('member_subscriptions', 'expiry_warning_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='True once the 3-day expiry warning email has been dispatched',
               existing_nullable=False)
    op.alter_column('member_subscriptions', 'created_by_id',
               existing_type=sa.UUID(),
               comment='Admin user who assigned this subscription',
               existing_nullable=True)
    op.drop_index('uq_one_active_sub_per_member', table_name='member_subscriptions', postgresql_where="(status = 'active'::subscription_status)")
    op.alter_column('membership_plan_templates', 'name',
               existing_type=sa.TEXT(),
               comment='Display name e.g. Silver, Gold, Platinum',
               existing_nullable=False)
    op.alter_column('membership_plan_templates', 'duration_months',
               existing_type=sa.INTEGER(),
               comment='Fixed duration in months: 3, 6, or 12 — immutable after creation',
               existing_nullable=False)
    op.alter_column('membership_plan_templates', 'base_price_inr',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Default price in INR; tenants may override this if granted permission',
               existing_nullable=False)
    op.alter_column('membership_plan_templates', 'features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="JSON array of feature strings e.g. ['Unlimited shortlists', 'Email alerts']",
               existing_nullable=True)
    op.alter_column('membership_plan_templates', 'max_interests',
               existing_type=sa.INTEGER(),
               comment='Max interest requests a member may send per subscription period; NULL = unlimited',
               existing_comment='Max interest requests per subscription period; NULL = unlimited',
               existing_nullable=True)
    op.alter_column('membership_plan_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('membership_plan_templates', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Display order (ascending); Silver=1, Gold=2, Platinum=3',
               existing_nullable=False)
    op.alter_column('partner_preferences', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('partner_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_partner_preferences_tenant', table_name='partner_preferences')
    op.drop_constraint('partner_preferences_profile_id_key', 'partner_preferences', type_='unique')
    op.create_index(op.f('ix_partner_preferences_profile_id'), 'partner_preferences', ['profile_id'], unique=True)
    op.create_index(op.f('ix_partner_preferences_tenant_id'), 'partner_preferences', ['tenant_id'], unique=False)
    op.alter_column('password_reset_tokens', 'token_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='SHA-256 hex of raw URL-safe token',
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'is_used',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('profiles', 'height_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('profiles', 'weight_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('profiles', 'marital_status',
               existing_type=postgresql.ENUM('never_married', 'divorced', 'widowed', 'awaiting_divorce', name='maritalstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('profiles', 'dhosam',
               existing_type=sa.VARCHAR(length=50),
               comment='Astrological dosha/dhosam',
               existing_nullable=True)
    op.alter_column('profiles', 'working_at',
               existing_type=sa.VARCHAR(length=200),
               comment='Employer / organisation name',
               existing_nullable=True)
    op.alter_column('profiles', 'country',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('profiles', 'native_place',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('profiles', 'current_location',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('profiles', 'siblings_details',
               existing_type=sa.TEXT(),
               comment='Free-text sibling info (count, married status, etc.)',
               existing_nullable=True)
    op.alter_column('profiles', 'photo_keys',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment='S3 object keys for photos (max 10)',
               existing_nullable=True)
    op.alter_column('profiles', 'horoscope_key',
               existing_type=sa.VARCHAR(length=512),
               comment='S3 object key for horoscope PDF/image',
               existing_nullable=True)
    op.alter_column('profiles', 'personal_visible',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('profiles', 'photo_visible',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('profiles', 'birth_visible',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('profiles', 'professional_visible',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('profiles', 'family_visible',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('profiles', 'contact_visible',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('profiles', 'horoscope_visible',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('profiles', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'suspended', 'matched', name='profilestatus'),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('profiles_user_id_key', 'profiles', type_='unique')
    op.drop_index('ix_profiles_user_id', table_name='profiles')
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.drop_column('profiles', 'education')
    op.drop_column('profiles', 'annual_income_inr')
    op.drop_column('profiles', 'occupation')
    op.drop_column('profiles', 'employer')
    op.drop_column('profiles', 'nakshatra')
    op.drop_column('profiles', 'siblings')
    op.drop_column('profiles', 'birth_time')
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=1024),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shortlists', 'status',
               existing_type=postgresql.ENUM('shortlisted', 'accepted', 'rejected', name='shortliststatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shortlists', 'note',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('shortlists', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shortlists', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_shortlists_from_profile', table_name='shortlists')
    op.drop_index('ix_shortlists_to_profile', table_name='shortlists')
    op.create_index(op.f('ix_shortlists_from_profile_id'), 'shortlists', ['from_profile_id'], unique=False)
    op.create_index(op.f('ix_shortlists_to_profile_id'), 'shortlists', ['to_profile_id'], unique=False)
    op.create_foreign_key(None, 'shortlists', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tenant_plan_overrides', 'custom_price_inr',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='NULL → use template base price; otherwise this is the tenant-specific price',
               existing_nullable=True)
    op.alter_column('tenant_plan_overrides', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('tenants', sa.Column('upi_name', sa.String(length=200), nullable=True, comment='Name associated with UPI ID'))
    op.add_column('tenants', sa.Column('upi_qr_key', sa.String(length=512), nullable=True, comment='S3 object key for UPI payment QR code'))
    op.add_column('tenants', sa.Column('payment_whatsapp', sa.String(length=20), nullable=True, comment='WhatsApp number for receiving payment screenshots'))
    op.alter_column('tenants', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               comment='Globally unique tenant identifier',
               existing_nullable=False)
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='Human-readable centre name',
               existing_nullable=False)
    op.alter_column('tenants', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment='URL-safe identifier used in subdomain / header',
               existing_nullable=False)
    op.alter_column('tenants', 'domain',
               existing_type=sa.VARCHAR(length=255),
               comment='Custom domain if white-labelled',
               existing_nullable=True)
    op.alter_column('tenants', 'contact_person',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               comment='Primary contact person name')
    op.alter_column('tenants', 'contact_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('tenants', 'castes',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment='Caste communities served by this centre',
               existing_nullable=True)
    op.alter_column('tenants', 'plan',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='starter | growth | enterprise',
               existing_nullable=False)
    op.alter_column('tenants', 'max_users',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenants', 'max_admins',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenants', 'can_override_plan_prices',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Grants tenant admin the ability to set custom membership plan prices',
               existing_nullable=False)
    op.alter_column('tenants', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('tenants_slug_key', 'tenants', type_='unique')
    op.drop_index('ix_tenants_slug', table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.drop_column('tenants', 'contact_phone')
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('super_admin', 'admin', 'member', name='userrole'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('super_admin', 'admin', 'member', name='userrole'),
               server_default=sa.text("'member'::userrole"),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.add_column('tenants', sa.Column('contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index('ix_tenants_slug', 'tenants', ['slug'], unique=False)
    op.create_unique_constraint('tenants_slug_key', 'tenants', ['slug'])
    op.alter_column('tenants', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('tenants', 'can_override_plan_prices',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='Grants tenant admin the ability to set custom membership plan prices',
               existing_nullable=False)
    op.alter_column('tenants', 'max_admins',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=False)
    op.alter_column('tenants', 'max_users',
               existing_type=sa.INTEGER(),
               server_default=sa.text('500'),
               existing_nullable=False)
    op.alter_column('tenants', 'plan',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'starter'::character varying"),
               comment=None,
               existing_comment='starter | growth | enterprise',
               existing_nullable=False)
    op.alter_column('tenants', 'castes',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment=None,
               existing_comment='Caste communities served by this centre',
               existing_nullable=True)
    op.alter_column('tenants', 'contact_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('tenants', 'contact_person',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               comment=None,
               existing_comment='Primary contact person name')
    op.alter_column('tenants', 'domain',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Custom domain if white-labelled',
               existing_nullable=True)
    op.alter_column('tenants', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='URL-safe identifier used in subdomain / header',
               existing_nullable=False)
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Human-readable centre name',
               existing_nullable=False)
    op.alter_column('tenants', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               comment=None,
               existing_comment='Globally unique tenant identifier',
               existing_nullable=False)
    op.drop_column('tenants', 'payment_whatsapp')
    op.drop_column('tenants', 'upi_qr_key')
    op.drop_column('tenants', 'upi_name')
    op.alter_column('tenant_plan_overrides', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('tenant_plan_overrides', 'custom_price_inr',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='NULL → use template base price; otherwise this is the tenant-specific price',
               existing_nullable=True)
    op.drop_constraint(None, 'shortlists', type_='foreignkey')
    op.drop_index(op.f('ix_shortlists_to_profile_id'), table_name='shortlists')
    op.drop_index(op.f('ix_shortlists_from_profile_id'), table_name='shortlists')
    op.create_index('ix_shortlists_to_profile', 'shortlists', ['to_profile_id'], unique=False)
    op.create_index('ix_shortlists_from_profile', 'shortlists', ['from_profile_id'], unique=False)
    op.alter_column('shortlists', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('shortlists', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('shortlists', 'note',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('shortlists', 'status',
               existing_type=postgresql.ENUM('shortlisted', 'accepted', 'rejected', name='shortliststatus'),
               server_default=sa.text("'shortlisted'::shortliststatus"),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.add_column('profiles', sa.Column('birth_time', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('siblings', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('nakshatra', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('employer', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('occupation', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('annual_income_inr', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('education', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.create_index('ix_profiles_user_id', 'profiles', ['user_id'], unique=False)
    op.create_unique_constraint('profiles_user_id_key', 'profiles', ['user_id'])
    op.alter_column('profiles', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'suspended', 'matched', name='profilestatus'),
               server_default=sa.text("'active'::profilestatus"),
               existing_nullable=False)
    op.alter_column('profiles', 'horoscope_visible',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('profiles', 'contact_visible',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('profiles', 'family_visible',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('profiles', 'professional_visible',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('profiles', 'birth_visible',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('profiles', 'photo_visible',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('profiles', 'personal_visible',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('profiles', 'horoscope_key',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='S3 object key for horoscope PDF/image',
               existing_nullable=True)
    op.alter_column('profiles', 'photo_keys',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment=None,
               existing_comment='S3 object keys for photos (max 10)',
               existing_nullable=True)
    op.alter_column('profiles', 'siblings_details',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Free-text sibling info (count, married status, etc.)',
               existing_nullable=True)
    op.alter_column('profiles', 'current_location',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('profiles', 'native_place',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('profiles', 'country',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'India'::character varying"),
               existing_nullable=False)
    op.alter_column('profiles', 'working_at',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Employer / organisation name',
               existing_nullable=True)
    op.alter_column('profiles', 'dhosam',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Astrological dosha/dhosam',
               existing_nullable=True)
    op.alter_column('profiles', 'marital_status',
               existing_type=postgresql.ENUM('never_married', 'divorced', 'widowed', 'awaiting_divorce', name='maritalstatus'),
               server_default=sa.text("'never_married'::maritalstatus"),
               existing_nullable=False)
    op.alter_column('profiles', 'weight_kg',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('profiles', 'height_cm',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('profiles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('password_reset_tokens', 'is_used',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'token_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='SHA-256 hex of raw URL-safe token',
               existing_nullable=False)
    op.drop_index(op.f('ix_partner_preferences_tenant_id'), table_name='partner_preferences')
    op.drop_index(op.f('ix_partner_preferences_profile_id'), table_name='partner_preferences')
    op.create_unique_constraint('partner_preferences_profile_id_key', 'partner_preferences', ['profile_id'])
    op.create_index('ix_partner_preferences_tenant', 'partner_preferences', ['tenant_id'], unique=False)
    op.alter_column('partner_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_preferences', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('membership_plan_templates', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='Display order (ascending); Silver=1, Gold=2, Platinum=3',
               existing_nullable=False)
    op.alter_column('membership_plan_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('membership_plan_templates', 'max_interests',
               existing_type=sa.INTEGER(),
               comment='Max interest requests per subscription period; NULL = unlimited',
               existing_comment='Max interest requests a member may send per subscription period; NULL = unlimited',
               existing_nullable=True)
    op.alter_column('membership_plan_templates', 'features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment="JSON array of feature strings e.g. ['Unlimited shortlists', 'Email alerts']",
               existing_nullable=True)
    op.alter_column('membership_plan_templates', 'base_price_inr',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Default price in INR; tenants may override this if granted permission',
               existing_nullable=False)
    op.alter_column('membership_plan_templates', 'duration_months',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Fixed duration in months: 3, 6, or 12 — immutable after creation',
               existing_nullable=False)
    op.alter_column('membership_plan_templates', 'name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Display name e.g. Silver, Gold, Platinum',
               existing_nullable=False)
    op.create_index('uq_one_active_sub_per_member', 'member_subscriptions', ['user_id', 'tenant_id'], unique=True, postgresql_where="(status = 'active'::subscription_status)")
    op.alter_column('member_subscriptions', 'created_by_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Admin user who assigned this subscription',
               existing_nullable=True)
    op.alter_column('member_subscriptions', 'expiry_warning_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='True once the 3-day expiry warning email has been dispatched',
               existing_nullable=False)
    op.alter_column('member_subscriptions', 'status',
               existing_type=postgresql.ENUM('active', 'expired', 'cancelled', name='subscription_status'),
               server_default=sa.text("'active'::subscription_status"),
               existing_nullable=False)
    op.alter_column('member_subscriptions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Subscription expiry date = starts_at + duration_months',
               existing_nullable=False)
    op.alter_column('member_subscriptions', 'starts_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Subscription start date (UTC)',
               existing_nullable=False)
    op.alter_column('member_subscriptions', 'price_paid_inr',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Price snapshot at time of assignment for billing history accuracy',
               existing_nullable=False)
    op.drop_constraint(None, 'file_records', type_='foreignkey')
    op.drop_constraint(None, 'file_records', type_='foreignkey')
    op.drop_index(op.f('ix_file_records_profile_id'), table_name='file_records')
    op.create_index('ix_file_records_profile', 'file_records', ['profile_id'], unique=False)
    op.alter_column('file_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('file_records', 'scan_status',
               existing_type=postgresql.ENUM('pending', 'clean', 'infected', 'error', name='scanstatus'),
               server_default=sa.text("'pending'::scanstatus"),
               existing_nullable=False)
    op.alter_column('file_records', 'purpose',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='profile_photo | horoscope')
    op.alter_column('file_records', 'size_bytes',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('file_records', 'mime_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('file_records', 'original_filename',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('file_records', 'object_key',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='Full S3 object key including prefix',
               existing_nullable=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
